image: kevr2d2/ubuntu-node:jammy
cache:
  key: system-v1
  paths:
    - /var/cache/apt/archives

stages:
  - lint
  - build
  - test

lint:
  stage: lint
  before_script:
    - apt-get -y update
    - apt-get -y install clang-format-16
  script:
    - find src -type f -name '*.h' -o -name '*.cpp' | xargs clang-format-16 -Werror --dry-run

build:
  stage: build
  before_script:
    - apt-get -y update
    - apt-get -y install meson pkg-config libpam-dev libncurses-dev
    - install -m666 pc/ubuntu-jammy.pam.pc /usr/lib/pkgconfig/pam.pc
    - chown -R test:test .
  script:
    - sudo -u test meson setup -Ddisable_tests=true build_exe
    - sudo -u test ninja -j $(nproc) -C build_exe

test:
  stage: test
  before_script:
    - apt-get -y update
    - apt-get -y install gcovr meson pkg-config libpam-dev
    - install -m666 pc/ubuntu-jammy.pam.pc /usr/lib/pkgconfig/pam.pc
  script:
    # Configure meson build for tests
    - sudo -u test meson setup -Ddisable_bin=true -Db_coverage=true build

    # Build and run tests
    - sudo -u test ninja -j $(nproc) -C build
    - sudo -u test ninja -C build test

    # Collect test coverage
    - sudo -u test ninja -C build coverage-xml
    - sudo -u test ninja -C build coverage-text
    - head -n -1 build/meson-logs/coverage.txt
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    expire_in: 2 days
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/meson-logs/coverage.xml
