on: [push]
jobs:
  test:
    runs-on: docker
    container:
      image: kevr2d2/ubuntu-node:jammy
    steps:
      - name: Package cache
        id: pkgcache
        uses: actions/cache@v3
        with:
          path: ~/packages
          key: ${{ runner.os }}-ubuntu-22.04-packages-v2

      - name: Restore cache
        if: steps.pkgcache.outputs.cache-hit == 'true'
        run: cp -vrf ~/packages/* /var/cache/apt/archives/

      - name: Install dependencies
        run: |
          apt-get -y update
          apt-get -y install git meson libncurses-dev gcovr lcov

      - name: Save cache
        run: |
          mkdir -p ~/packages
          cp -vrf /var/cache/apt/archives/*.deb ~/packages/

      - name: Checkout commit
        uses: actions/checkout@v3

      - run: meson setup -Db_coverage=true build
      - run: ninja -C build
      - run: ninja -C build test
